name: flutter_map_overlay
description: Application Flutter pour ajouter des overlays d'images sur OpenStreetMap
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Carte OpenStreetMap
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Sélection de fichiers
  file_picker: ^10.3.3

  # Gestion d'images
  image: ^4.1.7

  # Persistance des données
  shared_preferences: ^2.2.2

  # Gestion de fichiers
  path_provider: ^2.1.2

  # Permissions
  permission_handler: ^12.0.1

  # Géolocalisation
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
